### ISSUE TITLE
PyGLMaze camera issue 

### ISSUE THREAD

**Issue by CodeGuru12** [Blakkis/PyGLMaze#1]
I left you a comment on reddit where I found your  code from, but figured I'd drop you a line here with the update. (probably just a typo)

Current Line 45 in camera.py

    def updateCamera(self, delta, position):
        self.position.xz = position.xz
        self.position.y = self.p_height + position.y

Should be

    def updateCamera(self, delta, position):
        self.position.x = position.x
        self.position.z = position.z
        self.position.y = self.p_height + position.y

**Comment by Blakkis** [comment]
Interesting. Those are called "swizzle" operations "https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Swizzling"
this provides good overview of glm: "https://github.com/g-truc/glm" (C++)
I'm using this one: "https://pypi.org/project/PyGLM/" (Python)

I honestly haven't spent that much time with it on python side, but everything worked for me exactly the same way they worked on C++ side. So i'm not sure what's going on, on your side.

Dealing with in C++ side of things you have to explicitly enable swizzling, in python they seemed to work out from the box.

Thanks for the info.
